site_name: Cats API

nav:
  - Intro: "index.md"
  - How-To Guides:
      - Basic User Guides: "%include https://github.com/emil-jacero/repo1.git?ref=main&docs_dir=/docs/how-to-guides/*"
      - Advanced User Guides: "%include https://github.com/emil-jacero/repo2.git?ref=main&docs_dir=/docs/how-to-guides/*"
  - Authentication: "authentication.md"
  - Components: "*include ./components/*/mkdocs.yml"
  - API:
      - v1: "!include ./v1/mkdocs.yml"
      - v2: "!include ./v2/mkdocs.yml"
      - v3: "!include ./v3/mkdocs.yml"

plugins:
  - monorepo
